# API Service Definition Example

[Main]
    id = "clivern_poodle"
    name = "clivern - poodle"
    description = ""
    timeout = "30s"
    service_url = "https://example.com/api/v1"
    # These headers will be applied to all endpoints http calls
    headers = [ ["Content-Type", "application/json"] ]

[Security]
    # Supported Types are basic, bearer and api_key and none
    scheme = "none"

    [Security.Basic]
        username = "{$authUsername:default}"
        password = "{$authPassword:default}"
        header = ["Authorization", "Basic base64(username:password)"]

    [Security.ApiKey]
        header = ["X-API-KEY", "{$authApiKey:default}"]

    # In case of bearer authentication, it is recommended to create another
    # service or endpoint to generate the bearer tokens
    [Security.Bearer]
        header = ["Authorization", "Bearer {$authBearerToken:default}"]

[[Endpoint]]
    id = "GetSystemHealth"
    name = "Get system health"
    description = ""
    method = "get"
    # Security will be skipped for this endpoint
    public = true
    headers = []
    parameters = []
    uri = "/_health"
    body = ""

[[Endpoint]]
    id = "CreateItem"
    name = "Create an item"
    description = ""
    method = "post"
    headers = []
    parameters = []
    uri = "/item"
    body = """
    {
        "name": "{$name}",
        "type": "{$type:default}"
    }
    """

[[Endpoint]]
    id = "GetItems"
    name = "Get a list of items"
    description = ""
    method = "get"
    headers = []
    parameters = [ ["limit", "{$limit:100}"], ["offset", "{$offset:0}"] ]
    uri = "/item"
    body = ""

[[Endpoint]]
    id = "GetItem"
    name = "Get an item"
    description = ""
    method = "get"
    headers = []
    parameters = []
    uri = "/item/{$id}"
    body = ""

[[Endpoint]]
    id = "DeleteItem"
    name = "Delete an item"
    description = ""
    method = "delete"
    headers = []
    parameters = []
    uri = "/item/{$id}"
    body = ""

[[Endpoint]]
    id = "UpdateItem"
    name = "Update an item"
    description = ""
    method = "put"
    headers = []
    parameters = []
    uri = "/item/{$id}"
    body = """
    {
        "name": "{$name}",
        "type": "{$type:default}"
    }
    """