name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.17', '1.18']
    name: Go ${{ matrix.go }} run
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Get dependencies
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          make install_revive

      - name: Run make ci
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          go get -t .
          make ci
          git status
          git diff > diff.log
          cat diff.log
          git clean -fd
          git reset --hard
          make verify
